### ISSUE TITLE
Starting / stoping containers from images

### ISSUE THREAD

**Issue by waghanza** [jeromegn/docker.cr#3]
Hi,

I try to start a **container** from an `existing` image.

The following code
~~~crystal
container = Docker::Container.from_json({"Image" => target.name})
~~~

Crash with
~~~crystal
in /usr/share/crystal/src/json/pull_parser.cr:13: no overload matches 'JSON::Lexer.new' with type Hash(String, String)
Overloads are:
 - JSON::Lexer.new(string : String)
 - JSON::Lexer.new(io : IO)
 - JSON::Lexer.new()

    @lexer = Lexer.new input
~~~

Regards,

**Comment by jeromegn** [comment]
Looks like you're passing an Hash when it's expecting a JSON string or IO.

TBH I haven't touched this library in 2 years now. I don't remember exactly how it worked.

I'm not sure this particular feature you're looking for is available.
